[tool.poetry]
name = "askme"
version = "0.1.0"
description = ""
authors = ["johanngorban <ivangorbanwork@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.2.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
